# THROWAWAY PROTOTYPE: native R read/write without Seurat or Python conversion.
args <- commandArgs(trailingOnly = TRUE)
options(warn = 1)
library(anndataR)
library(rhdf5)
cat("R:", as.character(getRversion()), "anndataR:", as.character(packageVersion("anndataR")),
    "rhdf5:", as.character(packageVersion("rhdf5")),
    "reticulate:", as.character(packageVersion("reticulate")), "\n")
cat("Reticulate Python initialized before:", reticulate::py_available(initialize = FALSE), "\n")
cat("HDF5 obs attributes:\n")
print(h5readAttributes(args[[1]], "obs"))
a <- read_h5ad(args[[1]], as = "InMemoryAnnData")
print(a)
str(a$obs)
cat("raw binding exposed:", "raw" %in% names(a), "\n")
str(a$uns)
out <- file.path(args[[2]], paste0(args[[3]], "_roundtrip"))
dir.create(out, showWarnings = FALSE)
unlink(file.path(out, "data.h5ad"))
write_h5ad(a, file.path(out, "data.h5ad"))
cat("Unmodified whole-object roundtrip written\n")
a$obsm[["X_r_probe"]] <- as.matrix(a$X)[, 1:2, drop = FALSE]
a$uns[["r_probe"]] <- list(method = "native R addition", version = 1L)
out <- file.path(args[[2]], paste0(args[[3]], "_r_modified"))
dir.create(out, showWarnings = FALSE)
unlink(file.path(out, "data.h5ad"))
write_h5ad(a, file.path(out, "data.h5ad"))
cat("R-modified whole-object roundtrip written\n")
cat("Reticulate Python initialized after:", reticulate::py_available(initialize = FALSE), "\n")
